[package]
name = "cargo-update-installed"
version = "0.1.0"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
lazy_static = "1.4.0"
regex = "1.4.3"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.21"
url = "2.2.1"
